services:
  db:
    image: mariadb:10.5
    environment:
      MYSQL_DATABASE: my_db
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    command:
      ["gunicorn", "bcfg_chat_api.wsgi:application", "--bind", "0.0.0.0:80"]
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: my_db
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
      DEBUG: "True"
      ALLOWED_HOSTS: "localhost,127.0.0.1"
      OPENAI_API_KEY: "sk-svcacct-1IPVWhZrGhpKqv9OsyFNej3covM8DXXGnZDjKLAsD4Im_0xdFzQV3OSfrb26Mr1XGqRT3BlbkFJbxy4LMliwWxWlA2dwBz3vXpLm0Heg7immHGySQJwr4MTHj4WOWnZ4elAl2kkepGJOwAA"

    volumes:
      - .:/app
    ports:
      - "8000:80"
    depends_on:
      - db

volumes:
  db_data:
