# Generated by Django 5.1.3 on 2024-11-21 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_activity_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chat.user'),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chat.user'),
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chat.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chat.user')),
            ],
        ),
    ]
