# Generated by Django 5.1.3 on 2024-12-02 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_assistant_user_alter_transcript_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistant',
            name='current_activity_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assistant',
            name='exchange_count',
            field=models.IntegerField(default=0),
        ),
    ]
