# Generated by Django 5.1.3 on 2024-12-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_assistant_current_activity_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistant',
            name='session_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='transcript',
            name='session_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='assistant',
            name='exchange_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
