# Generated by Django 5.1.3 on 2024-12-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_assistant_session_count_transcript_session_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='priority',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='prompt',
            name='num_activities',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='prompt',
            name='num_rounds',
            field=models.IntegerField(default=4),
        ),
    ]
